DECLARE
  table_missing EXCEPTION;
  PRAGMA EXCEPTION_INIT(table_missing, -942);
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "TB_TA_PM_RESOURCE_ALLOCATIONS" CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN table_missing THEN
    NULL;
END;
/

DECLARE
  table_missing EXCEPTION;
  PRAGMA EXCEPTION_INIT(table_missing, -942);
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE "TB_TA_PM_PLANNING_WINDOWS" CASCADE CONSTRAINTS PURGE';
EXCEPTION
  WHEN table_missing THEN
    NULL;
END;
/
